-- 폐기물 추적 마스터
CREATE TABLE IF NOT EXISTS MOD_WASTE_TRACKING (
    TRACKING_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    TRACKING_NO       TEXT    NOT NULL UNIQUE,
    WASTE_TYPE        TEXT    NOT NULL,
    CURRENT_STAGE     TEXT    NOT NULL,
    STATUS            TEXT    NOT NULL DEFAULT 'INITIATED',
    SOURCE_NAME       TEXT    NOT NULL,
    TOTAL_WEIGHT_KG   REAL,
    REMARKS           TEXT,
    COMPLETED_AT      TEXT,
    CREATED_BY        TEXT,
    CREATED_AT        TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UPDATED_AT        TEXT,
    DEL_YN            TEXT    NOT NULL DEFAULT 'N'
);

-- 1단계: 배출
CREATE TABLE IF NOT EXISTS MOD_WASTE_DISCHARGE (
    DISCHARGE_ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    TRACKING_ID       INTEGER NOT NULL REFERENCES MOD_WASTE_TRACKING(TRACKING_ID),
    DISCHARGE_DATE    TEXT    NOT NULL,
    CENTER_CODE       TEXT    NOT NULL,
    CENTER_NAME       TEXT    NOT NULL,
    DISCHARGE_MANAGER TEXT,
    WEIGHT_KG         REAL    NOT NULL,
    WASTE_TYPE        TEXT    NOT NULL,
    REMARKS           TEXT,
    CREATED_AT        TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    DEL_YN            TEXT    NOT NULL DEFAULT 'N'
);

-- 2단계: 수거/운송
CREATE TABLE IF NOT EXISTS MOD_WASTE_COLLECTION (
    COLLECTION_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    TRACKING_ID         INTEGER NOT NULL REFERENCES MOD_WASTE_TRACKING(TRACKING_ID),
    COLLECTOR_CODE      TEXT    NOT NULL,
    COLLECTOR_NAME      TEXT    NOT NULL,
    VEHICLE_NO          TEXT,
    DRIVER_NAME         TEXT,
    COLLECTION_START_AT TEXT    NOT NULL,
    COLLECTION_END_AT   TEXT,
    COLLECTED_WEIGHT_KG REAL    NOT NULL,
    ORIGIN_ADDRESS      TEXT,
    DESTINATION_ADDRESS TEXT,
    DISTANCE_KM         REAL,
    CO2_EMISSION_KG     REAL,
    REMARKS             TEXT,
    CREATED_AT          TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    DEL_YN              TEXT    NOT NULL DEFAULT 'N'
);

-- 3단계: 압축 처리 (KNT)
CREATE TABLE IF NOT EXISTS MOD_WASTE_COMPRESSION (
    COMPRESSION_ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    TRACKING_ID         INTEGER NOT NULL REFERENCES MOD_WASTE_TRACKING(TRACKING_ID),
    PROCESSOR_CODE      TEXT    NOT NULL,
    PROCESSOR_NAME      TEXT    NOT NULL,
    PROCESS_START_AT    TEXT    NOT NULL,
    PROCESS_END_AT      TEXT,
    INPUT_WEIGHT_KG     REAL    NOT NULL,
    OUTPUT_WEIGHT_KG    REAL,
    LOSS_WEIGHT_KG      REAL,
    LOSS_RATE           REAL,
    COMPRESSION_DENSITY REAL,
    BALE_COUNT          INTEGER,
    REMARKS             TEXT,
    CREATED_AT          TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    DEL_YN              TEXT    NOT NULL DEFAULT 'N'
);

-- 4단계: 재활용
CREATE TABLE IF NOT EXISTS MOD_WASTE_RECYCLING (
    RECYCLING_ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    TRACKING_ID       INTEGER NOT NULL REFERENCES MOD_WASTE_TRACKING(TRACKING_ID),
    RECYCLER_CODE     TEXT    NOT NULL,
    RECYCLER_NAME     TEXT    NOT NULL,
    PROCESS_START_AT  TEXT    NOT NULL,
    PROCESS_END_AT    TEXT,
    INPUT_WEIGHT_KG   REAL    NOT NULL,
    OUTPUT_WEIGHT_KG  REAL,
    RECYCLING_RATE    REAL,
    RECYCLING_METHOD  TEXT,
    CO2_SAVING_KG     REAL,
    REMARKS           TEXT,
    CREATED_AT        TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    DEL_YN            TEXT    NOT NULL DEFAULT 'N'
);

-- 5단계: 제품 생산
CREATE TABLE IF NOT EXISTS MOD_WASTE_PRODUCTION (
    PRODUCTION_ID         INTEGER PRIMARY KEY AUTOINCREMENT,
    TRACKING_ID           INTEGER NOT NULL REFERENCES MOD_WASTE_TRACKING(TRACKING_ID),
    PRODUCER_CODE         TEXT    NOT NULL,
    PRODUCER_NAME         TEXT    NOT NULL,
    PRODUCT_NAME          TEXT    NOT NULL,
    PRODUCT_CODE          TEXT,
    PRODUCTION_START_AT   TEXT    NOT NULL,
    PRODUCTION_END_AT     TEXT,
    INPUT_WEIGHT_KG       REAL    NOT NULL,
    OUTPUT_WEIGHT_KG      REAL,
    PRODUCTION_QTY        INTEGER,
    DELIVERY_DESTINATION  TEXT,
    DELIVERY_DATE         TEXT,
    REMARKS               TEXT,
    CREATED_AT            TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    DEL_YN                TEXT    NOT NULL DEFAULT 'N'
);
