-- ============================================
-- 관리 마스터 테이블 + 사용자/인증
-- ============================================

-- 사용자 테이블
CREATE TABLE IF NOT EXISTS MOD_WASTE_USER (
    USER_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    LOGIN_ID      TEXT    NOT NULL UNIQUE,
    PASSWORD_HASH TEXT    NOT NULL,
    USER_NAME     TEXT    NOT NULL,
    ROLE          TEXT    NOT NULL DEFAULT 'USER',  -- ADMIN / USER
    EMAIL         TEXT,
    PHONE         TEXT,
    ACTIVE_YN     TEXT    NOT NULL DEFAULT 'Y',
    CREATED_AT    TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UPDATED_AT    TEXT,
    DEL_YN        TEXT    NOT NULL DEFAULT 'N'
);

-- 세션 토큰 테이블
CREATE TABLE IF NOT EXISTS MOD_WASTE_SESSION (
    SESSION_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID       INTEGER NOT NULL REFERENCES MOD_WASTE_USER(USER_ID),
    TOKEN         TEXT    NOT NULL UNIQUE,
    EXPIRES_AT    TEXT    NOT NULL,
    CREATED_AT    TEXT    NOT NULL DEFAULT (datetime('now','localtime'))
);

-- 물류센터(배출처) 마스터
CREATE TABLE IF NOT EXISTS MOD_WASTE_MST_CENTER (
    CENTER_ID     INTEGER PRIMARY KEY AUTOINCREMENT,
    CENTER_CODE   TEXT    NOT NULL UNIQUE,
    CENTER_NAME   TEXT    NOT NULL,
    ADDRESS       TEXT,
    CONTACT_NAME  TEXT,
    CONTACT_PHONE TEXT,
    REMARKS       TEXT,
    ACTIVE_YN     TEXT    NOT NULL DEFAULT 'Y',
    CREATED_AT    TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UPDATED_AT    TEXT,
    DEL_YN        TEXT    NOT NULL DEFAULT 'N'
);

-- 폐기물 종류 마스터
CREATE TABLE IF NOT EXISTS MOD_WASTE_MST_WASTE_TYPE (
    TYPE_ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    TYPE_CODE     TEXT    NOT NULL UNIQUE,
    TYPE_NAME     TEXT    NOT NULL,
    DESCRIPTION   TEXT,
    UNIT          TEXT    DEFAULT 'kg',
    ACTIVE_YN     TEXT    NOT NULL DEFAULT 'Y',
    CREATED_AT    TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UPDATED_AT    TEXT,
    DEL_YN        TEXT    NOT NULL DEFAULT 'N'
);

-- 수거 업체 마스터
CREATE TABLE IF NOT EXISTS MOD_WASTE_MST_COLLECTOR (
    COLLECTOR_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    COLLECTOR_CODE  TEXT    NOT NULL UNIQUE,
    COLLECTOR_NAME  TEXT    NOT NULL,
    ADDRESS         TEXT,
    CONTACT_NAME    TEXT,
    CONTACT_PHONE   TEXT,
    VEHICLE_COUNT   INTEGER DEFAULT 0,
    REMARKS         TEXT,
    ACTIVE_YN       TEXT    NOT NULL DEFAULT 'Y',
    CREATED_AT      TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UPDATED_AT      TEXT,
    DEL_YN          TEXT    NOT NULL DEFAULT 'N'
);

-- 압축 처리 업체 마스터
CREATE TABLE IF NOT EXISTS MOD_WASTE_MST_PROCESSOR (
    PROCESSOR_ID    INTEGER PRIMARY KEY AUTOINCREMENT,
    PROCESSOR_CODE  TEXT    NOT NULL UNIQUE,
    PROCESSOR_NAME  TEXT    NOT NULL,
    ADDRESS         TEXT,
    CONTACT_NAME    TEXT,
    CONTACT_PHONE   TEXT,
    CAPACITY_KG     REAL,
    REMARKS         TEXT,
    ACTIVE_YN       TEXT    NOT NULL DEFAULT 'Y',
    CREATED_AT      TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UPDATED_AT      TEXT,
    DEL_YN          TEXT    NOT NULL DEFAULT 'N'
);

-- 재활용 업체 마스터
CREATE TABLE IF NOT EXISTS MOD_WASTE_MST_RECYCLER (
    RECYCLER_ID     INTEGER PRIMARY KEY AUTOINCREMENT,
    RECYCLER_CODE   TEXT    NOT NULL UNIQUE,
    RECYCLER_NAME   TEXT    NOT NULL,
    ADDRESS         TEXT,
    CONTACT_NAME    TEXT,
    CONTACT_PHONE   TEXT,
    RECYCLING_TYPES TEXT,   -- 처리 가능 폐기물 종류(콤마 구분)
    REMARKS         TEXT,
    ACTIVE_YN       TEXT    NOT NULL DEFAULT 'Y',
    CREATED_AT      TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UPDATED_AT      TEXT,
    DEL_YN          TEXT    NOT NULL DEFAULT 'N'
);

-- 생산 업체 마스터
CREATE TABLE IF NOT EXISTS MOD_WASTE_MST_PRODUCER (
    PRODUCER_ID     INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUCER_CODE   TEXT    NOT NULL UNIQUE,
    PRODUCER_NAME   TEXT    NOT NULL,
    ADDRESS         TEXT,
    CONTACT_NAME    TEXT,
    CONTACT_PHONE   TEXT,
    PRODUCT_TYPES   TEXT,   -- 생산 가능 제품 종류
    REMARKS         TEXT,
    ACTIVE_YN       TEXT    NOT NULL DEFAULT 'Y',
    CREATED_AT      TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UPDATED_AT      TEXT,
    DEL_YN          TEXT    NOT NULL DEFAULT 'N'
);

-- 이슈 사항 관리
CREATE TABLE IF NOT EXISTS MOD_WASTE_MST_ISSUE (
    ISSUE_ID        INTEGER PRIMARY KEY AUTOINCREMENT,
    TRACKING_ID     INTEGER REFERENCES MOD_WASTE_TRACKING(TRACKING_ID),
    ISSUE_TYPE      TEXT    NOT NULL,   -- DELAY, QUALITY, WEIGHT_DIFF, ACCIDENT, OTHER
    SEVERITY        TEXT    NOT NULL DEFAULT 'MEDIUM',  -- LOW, MEDIUM, HIGH, CRITICAL
    TITLE           TEXT    NOT NULL,
    DESCRIPTION     TEXT,
    REPORTED_BY     TEXT,
    ASSIGNED_TO     TEXT,
    STATUS          TEXT    NOT NULL DEFAULT 'OPEN',  -- OPEN, IN_PROGRESS, RESOLVED, CLOSED
    RESOLVED_AT     TEXT,
    RESOLUTION      TEXT,
    CREATED_AT      TEXT    NOT NULL DEFAULT (datetime('now','localtime')),
    UPDATED_AT      TEXT,
    DEL_YN          TEXT    NOT NULL DEFAULT 'N'
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_user_login ON MOD_WASTE_USER(LOGIN_ID);
CREATE INDEX IF NOT EXISTS idx_session_token ON MOD_WASTE_SESSION(TOKEN);
CREATE INDEX IF NOT EXISTS idx_session_expires ON MOD_WASTE_SESSION(EXPIRES_AT);
CREATE INDEX IF NOT EXISTS idx_center_code ON MOD_WASTE_MST_CENTER(CENTER_CODE);
CREATE INDEX IF NOT EXISTS idx_waste_type_code ON MOD_WASTE_MST_WASTE_TYPE(TYPE_CODE);
CREATE INDEX IF NOT EXISTS idx_collector_code ON MOD_WASTE_MST_COLLECTOR(COLLECTOR_CODE);
CREATE INDEX IF NOT EXISTS idx_processor_code ON MOD_WASTE_MST_PROCESSOR(PROCESSOR_CODE);
CREATE INDEX IF NOT EXISTS idx_recycler_code ON MOD_WASTE_MST_RECYCLER(RECYCLER_CODE);
CREATE INDEX IF NOT EXISTS idx_producer_code ON MOD_WASTE_MST_PRODUCER(PRODUCER_CODE);
CREATE INDEX IF NOT EXISTS idx_issue_tracking ON MOD_WASTE_MST_ISSUE(TRACKING_ID);
CREATE INDEX IF NOT EXISTS idx_issue_status ON MOD_WASTE_MST_ISSUE(STATUS);
